### ISSUE TITLE
Moving login button to sidebar

### ISSUE THREAD

**Issue by hyongju** [mstaal/msal_streamlit_authentication#2]
Thanks for sharing the great work. I have a quick question. Can you tell me how to move login button to the sidebar? Thank you in advance!

**Comment by mstaal** [comment]
Hi @hyongju ! Thanks and you are welcome! I would have thought you could just put it into a sidebar of your choice. Do you have a (possibly small toy) sample you can share?

**Comment by hyongju** [comment]
@mstaal actually your suggestion worked right away? I just put the ```msl_authentication()``` under ```with st.sidebar:``` but there is one slight problem (not actually a problem :) ) As you can see from the attached photo, there is a large space between the botton and the next item (in this cast ```st.text()``` Can you advise? Thanks again!

<img width="394" alt="image" src="https://user-images.githubusercontent.com/1568391/235264299-c7348999-ccdd-4aa0-87a8-97e2177cac37.png">

**Comment by mstaal** [comment]
Hi @hyongju ! Great to hear that! I just (as in just now) released v1.0.8 of the plugin which allows one to attach HTML class or id attributes to the button (see the README for the interface). I guess this should allow you to customize the styling of the button. I have not tested it thoroughly, but could you give it a shot (and some feedback)? If not working, I will try to see what I can do.

**Comment by mstaal** [comment]
May I btw ask you which login provider you are using (this is purely out of interest). Is it Azure AD?

**Comment by mstaal** [comment]
As an alternative, I would imagine that styling your sidebar could change things. So you could e.g. split your sidebar into multiple components and then put the button into the one you prefer. I think the current button (which is by default just using Streamlits default button layout settings) puts itself into the center of whatever component it lives inside. So you would either like to adjust the stylings of the button or put it into something you are more in control of.

**Comment by hyongju** [comment]
Thanks @mstaal. Yes it is Azure AD single page app. I looked at your code at bit and looks like it is combinations of many different languages including React JS. Very cool. My apologies but I am not good enough to test the added functionality in v1.08, unfortunately. I am not sure what values I should put in for html id and class id. The only thing I figured out just now is I can achieve what I wanted by editing your css file directly.  Regardless thanks for your time!

**Comment by mstaal** [comment]
Fair enough. My idea was just to let you be able to style the element directly using CSS (and by setting the class of the button so that you could use CSS). But I will note your comments as a source of inspiration.
And thanks! Essentially, the idea behind the component is to use the React Framework to easily embed Microsofts JS based MSAL library so that it is directly accessible by Streamlit.

**Comment by hyongju** [comment]
I am glad that I gave you a small inspiration. But all in all, your library is very useful to me and should be the same for many users who are concerned I could have never imagined we could add azure ad auth to streamlit before! Thanks again for the quick responses too. Feel free to close this issue. I was not meant to bring this up as an issue rather as a new feature quest.

**Comment by mstaal** [comment]
I have made a small investigation, and I must admit a small awkward fact. I now realize that the CSS I have bundled as part of the project may be what's causing your issues. I will try to fix that soon. But I wonder what the right thing to do is (as in, should the button by default have no styling?). I will make some considerations on this.

**Comment by hyongju** [comment]
Hi, sorry about the delayed response. As you suggested, I think the no style button will be better than what we have there, but again I am content with your package already!

**Comment by mstaal** [comment]
Hi @hyongju ! Have you tried using the latest version of the app (v1.0.9)? Is it better for your purposes?

**Comment by tipani86** [comment]
> Hi @hyongju ! Have you tried using the latest version of the app (v1.0.9)? Is it better for your purposes?

I noticed the same (big border) issue, and will try to see if I can fix it by updating to 1.0.9, thanks for the tip (though I am not Hyongju :))

**Comment by mstaal** [comment]
Sorry @tipani86 ! I was too quick at auto-completing the username :-)))

**Comment by hyongju** [comment]
It has been a while, thanks @mstaal and @tipani86, I definitely think we can close this issue now :)
