### ISSUE TITLE
missing 'color: inherit' in index.css

### ISSUE THREAD

**Issue by keimatzmoto** [mstaal/msal_streamlit_authentication#38]
Appreciate your excellent work. 

Missing 'color: inherit' in index.css can set a white text color of the button in light gray background when using Windows 10 Dark Mode for Apps, which causes very low visibility. Any reason why color is not inherited?

**Comment by mstaal** [comment]
You are welcome! No, I have no particular reason for that - I will try to look into this soon.

**Comment by connortann** [comment]
Seconded. This unfortunately seems to effectively break the user interface for a significant fraction of users. As it seems like potentially a small fix, it would be wonderful if a new release could be made!
